version: 0.2

env:
  variables:
    PROJECT_NAME: frontend
    NAMESPACE: default

phases:
  install:
    commands:
      - set -eux

      - echo "Install kubectl"
      - curl -LO https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

      - kubectl version --client

  pre_build:
    commands:
      - echo "AWS Identity"
      - aws sts get-caller-identity

      - echo "Login to ECR"
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$REPOSITORY_URI"

      - echo "Generate Image Tag"
      - export IMAGE_TAG=$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c 1-7)
      - export IMAGE_TAG=${IMAGE_TAG:=latest}

      - echo "Update kubeconfig"
      - aws eks update-kubeconfig --name "$CLUSTER_NAME" --region "$AWS_DEFAULT_REGION"

      - kubectl cluster-info
      - kubectl get nodes
      - kubectl get ns

  build:
    commands:
      - echo "Build Docker image"
      - docker build --build-arg REACT_APP_BACKEND_URL="$REACT_APP_BACKEND_URL" -t "$REPOSITORY_URI:latest" .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

      - echo "Push image"
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG

      - echo "Render manifests"
      - mkdir -p rendered

      - export IMAGE_URI="$REPOSITORY_URI:$IMAGE_TAG"

      - sed "s|FRONTEND_APP|$FRONTEND_APP|g; s|IMAGE_URI|$IMAGE_URI|g; s|REACT_APP_BACKEND_URL|$REACT_APP_BACKEND_URL|g" deployment.yaml > rendered/deployment.yaml
      - sed "s|FRONTEND_APP|$FRONTEND_APP|g" service.yaml > rendered/service.yaml
      - sed "s|FRONTEND_TG_ARN|$FRONTEND_TG_ARN|g" frontend-targetgroupbinding.yaml > rendered/frontend-targetgroupbinding.yaml
      # - sed "s|FRONTEND_APP|$FRONTEND_APP|g" ingress.yaml > rendered/ingress.yaml

  post_build:
    commands:
      - echo "Deploy to EKS"

      - kubectl apply -f rendered/deployment.yaml -n "$NAMESPACE"
      - kubectl apply -f rendered/service.yaml -n "$NAMESPACE"
      - kubectl apply -f rendered/frontend-targetgroupbinding.yaml -n "$NAMESPACE"
      #- kubectl apply -f rendered/ingress.yaml -n "$NAMESPACE"

      - kubectl rollout status deployment/"$FRONTEND_APP" -n "$NAMESPACE" --timeout=300s

      - kubectl get pods -n "$NAMESPACE"
      - kubectl get svc -n "$NAMESPACE"
      #- kubectl get ingress -n "$NAMESPACE"

artifacts:
  files:
    - rendered/**/*
