apiVersion: apps/v1
kind: Deployment

metadata:
  name: Frontend_App
  labels:
    app: Frontend_App

spec:
  replicas: 2

  selector:
    matchLabels:
      app: Frontend_App

  template:
    metadata:
      labels:
        app: Frontend_App

    spec:
    containers:
      - name: Frontend_App
        image: IMAGE_URI

        ports:
          - containerPort: 3000

        env:
          - name: REACT_APP_BACKEND_URL
            value: "REACT_APP_BACKEND_URL"

        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10

        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 90
          timeoutSeconds: 5
          periodSeconds: 20

        startupProbe:
          tcpSocket:
            port: 3000
          failureThreshold: 60
          periodSeconds: 10
