apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: frontend-app-tgb
  namespace: default
  labels:
    app: FRONTEND_APP
    environment: production
spec:
  targetGroupARN: FRONTEND_TG_ARN
  targetType: ip
  serviceRef:
    name: FRONTEND_APP-service
    port: 80
  #networking:
  #  ingress:
  #    - from:
  #      - securityGroup:
  #          groupId:
